### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sirtthe9th** [Last-First/vba-webdata#1]
Hi, does anyone know if there is a module in here that could be used to help make an appointment tracker? My gf works at a nail salon and they want to keep track of appointments using Excel. So they need to be able to input certain criteria such as name, date, phone number, etc and then be able to visualize the appointments for a certain date range.

I figured I'd ask to see if I can get a bit of a head start instead of randomly looking through it.

Thanks, Thomas Reid

**Comment by erujs** [comment]
Hi @sirtthe9th sorry for the late response, I haven't used visual basic for application for a long time as it was only for a personal use. I'm a web developer guy so i mainly use javascript in development. In regards to your query I think that is possible with vba and there might be other modules out there that you might want to look at, try searching it in other repos or stackoverflow maybe. That's all I can say about it.

Cheers and Goodluck!

**Comment by erujs** [comment]
As this is not an issue with the repo, I'll be tagging this as close.

you can reach me through my email: a.m.jerus@gmail.com
